name: Hexa user crud

on:
  push:
    branches: [ "main", "test-action" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:1.83
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
